# CMake generated Testfile for 
# Source directory: /mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests
# Build directory: /mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/build-worker-4/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[pb_smoke_compile_pass]=] "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/build-worker-4/tests/pb_smoke_compile_pass")
set_tests_properties([=[pb_smoke_compile_pass]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;4;add_test;/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;0;")
add_test([=[pb_runtime_smoke]=] "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/build-worker-4/tests/pb_runtime_smoke")
set_tests_properties([=[pb_runtime_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;9;add_test;/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;0;")
add_test([=[pb_runtime_result_smoke]=] "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/build-worker-4/tests/pb_runtime_result_smoke")
set_tests_properties([=[pb_runtime_result_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;14;add_test;/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;0;")
add_test([=[pb_runtime_sequential_result_smoke]=] "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/build-worker-4/tests/pb_runtime_sequential_result_smoke")
set_tests_properties([=[pb_runtime_sequential_result_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;19;add_test;/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;0;")
add_test([=[pb_compile_fail_edge_mismatch]=] "/usr/bin/cmake" "-DTEST_SOURCE=/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/compile_fail/edge_mismatch.cpp" "-DTEST_COMPILER=/usr/bin/c++" "-DTEST_INCLUDE_DIR=/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/include" "-DEXPECT_DIAGNOSTIC=Pipeline edge mismatch" "-P" "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/run_compile_fail.cmake")
set_tests_properties([=[pb_compile_fail_edge_mismatch]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;21;add_test;/mnt/c/users/tonyt/documents/github/pipeline-c++/.omx/team/deliver-the-pipeline-1a2d869d/worktrees/worker-4/tests/CMakeLists.txt;0;")
