#pragma once

#include "pb/adapt/fn.hpp"
#include "pb/core/concepts.hpp"
#include "pb/core/describe.hpp"
#include "pb/core/fixed_string.hpp"
#include "pb/core/meta.hpp"
#include "pb/core/pipeline_state.hpp"
#include "pb/core/stage_traits.hpp"
#include "pb/core/validate.hpp"
#include "pb/runtime/error.hpp"
#include "pb/runtime/observer.hpp"
#include "pb/runtime/result.hpp"
#include "pb/runtime/sequential.hpp"

namespace pb {
using core::AdjacentStages;
using core::Connectable;
using core::RunnableStage;
using core::Stage;
using core::ValidPipeline;
using core::adjacent_stages_v;
using core::connectable_v;
using core::describe;
using core::fixed_string;
using core::from;
using core::is_pipeline_v;
using core::pipeline_descriptor;
using core::pipeline_empty_v;
using core::pipeline_input_t;
using core::pipeline_output_t;
using core::pipeline_size_v;
using core::pipeline_descriptor_view;
using core::pipeline;
using core::pipeline_state;
using core::pipeline_stage_descriptor_t;
using core::pipeline_stage_error_t;
using core::pipeline_stages_t;
using core::pipeline_stage_t;
using core::pipeline_traits;
using core::descriptor_view;
using core::runnable_stage_v;
using core::stage_descriptor;
using core::stage_error_t;
using core::stage_info;
using core::stage_info_t;
using core::stage_key;
using core::stage_record;
using core::stage_input_t;
using core::stage_name;
using core::stage_output_t;
using core::stage_traits;
using core::valid;
using runtime::category_name;
using runtime::describe;
using runtime::expected_like;
using runtime::error;
using runtime::error_category;
using runtime::has_category;
using runtime::has_message;
using runtime::has_stage;
using runtime::is_result_v;
using runtime::make_result;
using runtime::observer;
using runtime::result;
using runtime::stage_id;
using runtime::to_result;
} // namespace pb
