#include "pb/pipeline.hpp"

struct s1 { using input_type = int; using output_type = int; };
struct s2 { using input_type = int; using output_type = int; };
struct s3 { using input_type = int; using output_type = int; };
struct s4 { using input_type = int; using output_type = int; };
struct s5 { using input_type = int; using output_type = int; };
struct s6 { using input_type = int; using output_type = int; };
struct s7 { using input_type = int; using output_type = int; };
struct s8 { using input_type = int; using output_type = int; };
struct s9 { using input_type = int; using output_type = int; };
struct s10 { using input_type = int; using output_type = int; };
struct s11 { using input_type = int; using output_type = int; };
struct s12 { using input_type = int; using output_type = int; };
struct s13 { using input_type = int; using output_type = int; };
struct s14 { using input_type = int; using output_type = int; };
struct s15 { using input_type = int; using output_type = int; };
struct s16 { using input_type = int; using output_type = int; };
struct s17 { using input_type = int; using output_type = int; };
struct s18 { using input_type = int; using output_type = int; };
struct s19 { using input_type = int; using output_type = int; };
struct s20 { using input_type = int; using output_type = int; };
struct s21 { using input_type = int; using output_type = int; };
struct s22 { using input_type = int; using output_type = int; };
struct s23 { using input_type = int; using output_type = int; };
struct s24 { using input_type = int; using output_type = int; };
struct s25 { using input_type = int; using output_type = int; };
struct s26 { using input_type = int; using output_type = int; };
struct s27 { using input_type = int; using output_type = int; };
struct s28 { using input_type = int; using output_type = int; };
struct s29 { using input_type = int; using output_type = int; };
struct s30 { using input_type = int; using output_type = int; };
struct s31 { using input_type = int; using output_type = int; };
struct s32 { using input_type = int; using output_type = int; };
struct s33 { using input_type = int; using output_type = int; };
struct s34 { using input_type = int; using output_type = int; };
struct s35 { using input_type = int; using output_type = int; };
struct s36 { using input_type = int; using output_type = int; };
struct s37 { using input_type = int; using output_type = int; };
struct s38 { using input_type = int; using output_type = int; };
struct s39 { using input_type = int; using output_type = int; };
struct s40 { using input_type = int; using output_type = int; };
struct s41 { using input_type = int; using output_type = int; };
struct s42 { using input_type = int; using output_type = int; };
struct s43 { using input_type = int; using output_type = int; };
struct s44 { using input_type = int; using output_type = int; };
struct s45 { using input_type = int; using output_type = int; };
struct s46 { using input_type = int; using output_type = int; };
struct s47 { using input_type = int; using output_type = int; };
struct s48 { using input_type = int; using output_type = int; };
struct s49 { using input_type = int; using output_type = int; };
struct s50 { using input_type = int; using output_type = int; };

using p1 = typename pb::from<int>::then<s1>::chain;
using p2 = typename p1::then<s2>::chain;
using p3 = typename p2::then<s3>::chain;
using p4 = typename p3::then<s4>::chain;
using p5 = typename p4::then<s5>::chain;
using p6 = typename p5::then<s6>::chain;
using p7 = typename p6::then<s7>::chain;
using p8 = typename p7::then<s8>::chain;
using p9 = typename p8::then<s9>::chain;
using p10 = typename p9::then<s10>::chain;
using p11 = typename p10::then<s11>::chain;
using p12 = typename p11::then<s12>::chain;
using p13 = typename p12::then<s13>::chain;
using p14 = typename p13::then<s14>::chain;
using p15 = typename p14::then<s15>::chain;
using p16 = typename p15::then<s16>::chain;
using p17 = typename p16::then<s17>::chain;
using p18 = typename p17::then<s18>::chain;
using p19 = typename p18::then<s19>::chain;
using p20 = typename p19::then<s20>::chain;
using p21 = typename p20::then<s21>::chain;
using p22 = typename p21::then<s22>::chain;
using p23 = typename p22::then<s23>::chain;
using p24 = typename p23::then<s24>::chain;
using p25 = typename p24::then<s25>::chain;
using p26 = typename p25::then<s26>::chain;
using p27 = typename p26::then<s27>::chain;
using p28 = typename p27::then<s28>::chain;
using p29 = typename p28::then<s29>::chain;
using p30 = typename p29::then<s30>::chain;
using p31 = typename p30::then<s31>::chain;
using p32 = typename p31::then<s32>::chain;
using p33 = typename p32::then<s33>::chain;
using p34 = typename p33::then<s34>::chain;
using p35 = typename p34::then<s35>::chain;
using p36 = typename p35::then<s36>::chain;
using p37 = typename p36::then<s37>::chain;
using p38 = typename p37::then<s38>::chain;
using p39 = typename p38::then<s39>::chain;
using p40 = typename p39::then<s40>::chain;
using p41 = typename p40::then<s41>::chain;
using p42 = typename p41::then<s42>::chain;
using p43 = typename p42::then<s43>::chain;
using p44 = typename p43::then<s44>::chain;
using p45 = typename p44::then<s45>::chain;
using p46 = typename p45::then<s46>::chain;
using p47 = typename p46::then<s47>::chain;
using p48 = typename p47::then<s48>::chain;
using p49 = typename p48::then<s49>::chain;
using p50 = typename p49::then<s50>::chain;
using pipeline = p50;
static_assert(pb::core::is_valid_chain_v<pipeline>);

int main() { return 0; }
